# <font color='blue'>ESTUDO DE CASO COM NUMPY(PRÉ-PROCESSAMENTO)</font>

#### Para  este  Estudo  de  Caso trabalharemos  com  dados  reais  disponíveis  publicamente  no link abaixo: https://www.openintro.org/data/index.php?data=loans_full_schema

#### Esse  conjunto  de  dados  representa  milhares  de  empréstimos  feitos  por  meio  da plataforma  Lending  Club,  que  é  uma  plataforma  que  permite  que  indivíduos  emprestem  para outros indivíduos. 

#### Claro, nem todos os empréstimos são iguais. Alguém que fornece um baixo risco e que provavelmente vaipagar um empréstimo terá mais facilidade em obter um empréstimo com uma taxa de juros baixa do que alguém que parece ser mais arriscado. 

#### E para as pessoas com alto risco de não pagar o empréstimo? Essas pessoaspodem nem receber uma oferta de empréstimo, ou podem não aceitaruma oferta de empréstimo devido a uma alta taxa de juros. É importante ter em mente essa última parte, pois esse conjunto de dados representa  apenas  empréstimos  efetivamente  feitos,  ou  seja,  não  confunda  esses  dados  com pedidos de empréstimo!

#### Usamos   como   fonte   de   dados   o   dataset   disponível   no   link   acima,   mas   fizemos modificações nos dados para deixá-los ainda mais problemáticos. O dataset será fornecido a você junto com os demais arquivos do capítulo.

#### Além  disso  usaremos  um  dataset  com  cotação  do  dólar  em  relação  ao  Euro.  Extraímos uma pequena amostra de dados do site: https://finance.yahoo.com. O dataset será fornecido a você junto com os demais arquivos do capítulo.

#### Nosso trabalho é limpar e pré-processar os dados, deixando-os no formato ideal para um processo de análise posterior e várias decisões terão que ser tomadas no meio do caminho. Ao final do trabalho devemos salvar o dataset com os dados limpos e pré-processados.

In [1]:
#Versão da Linguagem Python
from platform import python_version
print('Versão da Linguagem Python Usada Neste Jupyter Notebook:', python_version())

Versão da Linguagem Python Usada Neste Jupyter Notebook: 3.9.7


In [2]:
# Para atualizar um pacote, execute o comando abaixo no terminal ou prompt de comando:
# pip install -U nome_pacote

# Para instalar a versão exata de um pacote, execute o comando abaixo no terminal ou prompt de comando:
# !pip install nome_pacote==versão_desejada

# Depois de instalar ou atualizar o pacote, reinicie o jupyter notebook.

# Instala o pacote watermark. 
# Esse pacote é usado para gravar as versões de outros pacotes usados neste jupyter notebook.
# !pip install -q -U watermark

In [3]:
# Import
import numpy as np

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
# Versões dos pacotes usados neste jupyter notebook
%reload_ext watermark
%watermark -a "Lucas Castro" --iversions

Author: Lucas Castro

numpy: 1.22.3



In [6]:
# Configuração de impressão do NumPy
np.set_printoptions(suppress = True, linewidth = 200, precision = 2)

## <font color='blue' text-align:center >Carregando o Dataset</font>

In [7]:
dados = np.genfromtxt("dados/dataset1.csv", 
                      delimiter=';', 
                      skip_header = 1, 
                      autostrip = True, 
                      encoding = 'cp1252')

In [8]:
type(dados)

numpy.ndarray

In [9]:
dados.shape

(10000, 14)

In [10]:
dados.view()

array([[48010226.  ,         nan,    35000.  , ...,         nan,         nan,     9452.96],
       [57693261.  ,         nan,    30000.  , ...,         nan,         nan,     4679.7 ],
       [59432726.  ,         nan,    15000.  , ...,         nan,         nan,     1969.83],
       ...,
       [50415990.  ,         nan,    10000.  , ...,         nan,         nan,     2185.64],
       [46154151.  ,         nan,         nan, ...,         nan,         nan,     3199.4 ],
       [66055249.  ,         nan,    10000.  , ...,         nan,         nan,      301.9 ]])

Observamos que muitas colunas estão com tipo <font color='red'>nan</font>. Isso se deve a caracteres especiais no conjunto de dados ea forma como o <font color='blue'>NumPy</font> carrega os dados numéricos e do tipo string. Vamos resolver isso.

## <font color='blue'>Verificando Valores Ausentes</font>

In [11]:
np.isnan(dados).sum()

88005

In [12]:
# Vamos retorna o maior valor +1 ignorando valores nan
# Usaremos esse valor arbitrário para preencher os valores ausentes no momento de carga de dados de variáveis
# numéricas e depois tratamos esse calor como valor ausente
valor_coringa = np.nanmax(dados) + 1
print(valor_coringa)

68616520.0


In [13]:
# Calculamos a média (variáveis numéricas) ignorando valores nan por coluna
# Usaremos isso para separar variáveis numéricas de variáveis do tipo string 
media_ignorando_nan = np.nanmean(dados, axis = 0)
print(media_ignorando_nan)

[54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]


In [14]:
# Colunas do tipo  string com valores ausentes
colunas_string = np.argwhere(np.isnan(media_ignorando_nan)).squeeze(); colunas_string

array([ 1,  3,  5,  8,  9, 10, 11, 12])

In [15]:
# Colunas numéricas
colunas_numericas = np.argwhere(np.isnan(media_ignorando_nan)==False).squeeze(); colunas_numericas

array([ 0,  2,  4,  6,  7, 13])

> Importamos novamente o dataset, separando colunas do tipo string de colunas numéricas.

In [16]:
# Carrega as colunas do tipo string
arr_str = np.genfromtxt("dados/dataset1.csv",
                       delimiter=';',
                       skip_header=1, 
                       autostrip= True,
                       usecols = colunas_string,
                       dtype = str,
                       encoding = 'cp1252')

In [17]:
arr_str

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [18]:
# Carrega as colunas do tipo numérico preenchendo os valores ausentes
arr_num = np.genfromtxt("dados/dataset1.csv",
                            delimiter = ';',
                            autostrip = True,
                            skip_header = 1,
                            usecols = colunas_numericas,
                            filling_values = valor_coringa, 
                            encoding = 'cp1252')

In [19]:
arr_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

> Agora exraímkos os nomes das colunas

In [20]:
# Carrega os nomes das colunas 
arr_col = np.genfromtxt("dados/dataset1.csv",
                       delimiter=';',
                       autostrip=True,
                       skip_footer= dados.shape[0],
                       dtype=str,
                       encoding='cp1252')

In [21]:
arr_col

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state', 'total_pymnt'], dtype='<U19')

In [22]:
# Separa cabeçalho de colnas str e num
header_str, header_num = arr_col[colunas_string], arr_col[colunas_numericas]

In [23]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [24]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## <font color = 'blue'>Função de Checkpoint</font>

In [25]:
# Função 
def checkpoint(file_name, checkpoint_header, checkpoint_data): 
    np.savez(file_name, checkpoint_header,data = checkpoint_data)
    checkpoint_var = np.load(file_name + ".npz")
    return(checkpoint_var)

In [26]:
checkpoint_inicial = checkpoint("dados/Checkpoint-inicial", header_str, arr_str)

In [27]:
checkpoint_inicial['data']

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

In [28]:
np.array_equal(checkpoint_inicial['data'], arr_str)

True

## <font color='blue'>Manipulando as colunas tipo string</font>

In [29]:
header_str

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [30]:
# Vamos ajustar o nome da coluna issue_d para facilitar a identificação da coluna
header_str[0] = "issue_date"; header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [31]:
arr_str

array([['May-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']], dtype='<U69')

## <font color='blue'>Pré-processamento da variável issue_date com </font> <font color='red'> Label Encoding</font>

In [32]:
# Extrai os valores únicos da variável
np.unique(arr_str[:, 0])

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15', 'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [33]:
# Vamos remover remover o sufixo -15 e converter em um array de strings
arr_str[:, 0] = np.chararray.strip(arr_str[:,0], "-15")

In [34]:
# Extrai os valores únicos da variável
np.unique(arr_str[:, 0])

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'], dtype='<U69')

In [35]:
# Criamos um array com os meses (incluindo um elemento como vazio o que estiver em branco)
meses = np.array(['','Jan', 'Feb','Mar','Apr', 'May', 'Jun', 'Jul', 'Aug','Sep' ,'Oct','Nov','Dec'])

In [36]:
# Loop pra converter os nomes dos meses em valores numéricos
# Chamamos isso de Label Encoding

for i in range(13): 
    arr_str[:, 0] = np.where(arr_str[:,0]==meses[i], i, arr_str[:, 0])

In [37]:
np.unique(arr_str[:, 0])

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

## <font color='blue'>Pré-processamento da variável loan_status com </font> <font color='red'>Binarização</font>

In [38]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [39]:
# Extrai os valores únicos da variável
np.unique(arr_str[:, 1])

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [40]:
# Número de elementos
np.unique(arr_str[:, 1]).size

9

In [41]:
# Criamos um array com apenas 3 status
status_bad = np.array(['', 'Charged Off','Default','Late (31-120 days)'])

In [42]:
# Checamos agora os valores da variável e comparamos com o array anterior convertendo a variável para valores binários
# Chamamos isso de binarização
arr_str[:, 1] = np.where(np.isin(arr_str[:,1], status_bad),0,1)

In [43]:
np.unique(arr_str[:, 1])

array(['0', '1'], dtype='<U69')

## <font color='blue'>Pré-processamento da variável term com </font> <font color='red'>Limpeza da String</font>

In [44]:
header_str

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [45]:
np.unique(arr_str[:, 2])

array(['', '36 months', '60 months'], dtype='<U69')

In [46]:
# Removemos a palavra 'months'n (observe o espaço antes da palavra)
arr_str[:, 2] = np.chararray.strip(arr_str[:, 2], " months")
arr_str[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [47]:
# Mudamos o título da variável 
header_str[2] = "term_months"

In [48]:
# Substiuímos os valores ausentes pelo maior valor, no caso 60
arr_str[:, 2] = np.where(arr_str[:, 2] == '', '60', arr_str[:, 2]); arr_str[:, 2]

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [49]:
# Extrai os valores únicos da varíavel
np.unique(arr_str[:, 2])

array(['36', '60'], dtype='<U69')

## <font color='blue'>Pré-processamento da variável grade/sub_grade com </font> <font color='red'>Dicionário (Tipo de Label Encoding)</font>

In [50]:
header_str 

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [51]:
# Extrai os valores únicos da variável
np.unique(arr_str[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [52]:
# Extrai os valores únicos da variável
np.unique(arr_str[:,4])

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
       'G2', 'G3', 'G4', 'G5'], dtype='<U69')

> Vamos ajustar a varíavel sub_grade

In [53]:
np.unique(arr_str[:,3])[1:]

array(['A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [54]:
# Loop para ajuste da variável sub_grade
for i in np.unique(arr_str[:,3])[1:]:
    arr_str[:,4] = np.where((arr_str[:,4] =='') & (arr_str[:,3] ==i), i + '5', arr_str[:,4])

In [55]:
# Retorna categorias e suas respectivas contagens 
np.unique(arr_str[:,4], return_counts = True)

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1',
        'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267, 250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5]))

In [56]:
# Substituímos valores por uma nova categoria
arr_str[:,4] = np.where(arr_str[:,4]=='','H1', arr_str[:,4])

In [57]:
# Extrai os valores únicos da variável
np.unique(arr_str[:,4])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

> Vamos remover a variável grade

In [58]:
# Não precisamos mais da variável grade. Podemosremover
arr_str = np.delete(arr_str,3, axis = 1)

In [59]:
# Nova variável na coluna de índice 3
arr_str[:,3]

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [60]:
# Não podemos esquecer de remover a coluna do array de nomes de colunas
header_str = np.delete(header_str, 3)

In [61]:
header_str[3]

'sub_grade'

> Por fim, converteremos a variável sub_grade para sua representação numérica

In [62]:
# Extrai os valores únicos da variável
np.unique(arr_str[:,3])

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5', 'G1', 'G2',
       'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [63]:
# Cria uma lista de chaves
keys = list(np.unique(arr_str[:,3]))     
keys[0]

'A1'

In [64]:
# Cria uma lista de valores
values = list(range(1, np.unique(arr_str[:,3]).shape[0] + 1)) 
values[0]

1

In [65]:
# Criamos então o dicionário
dict_sub_grade = dict(zip(keys, values))

In [66]:
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [67]:
# Loop para substituir a string com as categorias pela representação numérica (frequência)
for i in np.unique(arr_str[:,3]):
        arr_str[:,3] = np.where(arr_str[:,3] == i, dict_sub_grade[i], arr_str[:,3])

In [68]:
# Extrai os valores únicos da variável
np.unique(arr_str[:,3])

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22', '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36', '4', '5', '6',
       '7', '8', '9'], dtype='<U69')

## <font color='blue'>Pré-processamento da variável Verification status com </font> <font color='red'>Binarização</font>

In [69]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [70]:
np.unique(arr_str[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [71]:
# Checamos agora os valores da variável e comparamos com o array anterior convertendo a variável para valores binários
# Chamamos isso de binarização

not_verified = np.array(['','Not Verified'])

arr_str[:, 4] = np.where(np.isin(arr_str[:,4],not_verified),0,1)

In [72]:
# Extrai os valores únicos da variável
np.unique(arr_str[:,4])

array(['0', '1'], dtype='<U69')

## <font color='blue'>Pré-Processamento da variável url com </font><font color='red'>Extração de ID</font>

In [73]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url', 'addr_state'], dtype='<U19')

In [74]:
np.unique(arr_str[:, 5])

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=12606806', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=13026045',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=1312426', ..., 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8138291',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=8214572', 'https://www.lendingclub.com/browse/loanDetail.action?loan_id=849994'], dtype='<U69')

In [75]:
# Extraímos o id ao final de cada url
np.chararray.strip(arr_str[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [76]:
# Substituímos a url pelo valor do id na url
arr_str[:,5] = np.chararray.strip(arr_str[:,5], 
                                      "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

In [77]:
# Convertemos o tipo para int32
arr_str[:,5].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [78]:
# Parece que esse id está presente na primeira coluna do conjunto de dados.
# Vamos converter para int 32 e comparar
arr_num[:,0].astype(dtype = np.int32)

array([48010226, 57693261, 59432726, ..., 50415990, 46154151, 66055249], dtype=int32)

In [79]:
np.array_equal(arr_num[:, 0].astype(dtype = np.int32), arr_str[:,5].astype(dtype= np.int32))

True

> Sim, é a mesma informação. Vamos então remover uma das colunas.

In [80]:
# Remove do array de dados
arr_str = np.delete(arr_str, 5, axis = 1)

In [81]:
# Remove do array de nome de coluna
header_str = np.delete(header_str, 5)

In [82]:
# Nova coluna no índice 5
arr_str[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [83]:
# Nova lista de colunas
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [84]:
# Coluna id
arr_num[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [85]:
# Coluna id agora faz parte do array de numéricos
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

## <font color='blue'>Pré-Processamento da variável address com </font><font color='red'>Categorização</font>

In [86]:
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'addr_state'], dtype='<U19')

In [87]:
# Vamos ajustar o nome da coluna
header_str[5] = "state_address"

In [88]:
np.unique(arr_str[:,5])

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM',
       'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA', 'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

In [89]:
# Extrai nomes e contagens
state_names , state_count = np.unique(arr_str[:,5], return_counts = True)

In [90]:
# Ordem descrescente

state_count_sorted = np.argsort(-state_count)

In [91]:
# Imprime o resultado
state_names[state_count_sorted], state_count[state_count_sorted]

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ', 'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY', 'KS', 'OK',
        'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK', 'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,  216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,   84,   83,
          74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,   25,   24,   17,   16,   10]))

In [92]:
# Substituímos valores ausentes por zero
arr_str[:,5] = np.where(arr_str[:,5] == '', 0, arr_str[:,5])

In [93]:
# Separamos os estados por regiões
states_west = np.array(['WA', 'OR','CA','NV','ID','MT', 'WY','UT','CO', 'AZ','NM','HI','AK'])
states_south = np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest = np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])
states_east = np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])

In [94]:
# Agora substituímos cada estado pelo id da sua região
arr_str[:,5] = np.where(np.isin(arr_str[:,5], states_west), 1, arr_str[:,5])
arr_str[:,5] = np.where(np.isin(arr_str[:,5], states_south), 2, arr_str[:,5])
arr_str[:,5] = np.where(np.isin(arr_str[:,5], states_midwest), 3, arr_str[:,5])
arr_str[:,5] = np.where(np.isin(arr_str[:,5], states_east), 4, arr_str[:,5])

In [95]:
# Extrai os valores úinicos
np.unique(arr_str[:,5])

array(['0', '1', '2', '3', '4'], dtype='<U69')

## <font color='blue'> Convertendo o Array</font>

Nosso array de strings agora é um array numérico. Vamos ajustar o tipo de dado.

In [96]:
arr_str

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [97]:
arr_str = arr_str.astype(int); arr_str

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

## <font color='blue'>Checkpoint com Variáveis do Tipo String Limpas e Pré-Processadas</font>

*Checkpoint 2**

Concluída a primeira parte, vamos gravar o checkpooint.

In [98]:
checkpoint_strings = checkpoint("dados/Checkpoint-Strings", header_str, arr_str)

In [99]:
checkpoint_strings['arr_0']

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [100]:
np.array_equal(checkpoint_strings['data'], arr_str)

True

## <font color='blue'>Manipulando Colunas Numéricas</font>

In [101]:
# Visualixa os dados
arr_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [102]:
# Nomes das colunas
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [103]:
# Não temos valor ausente, pos ao carregar os dados substituímos por um valor arbitrário
np.isnan(arr_num).sum()

0

In [104]:
valor_coringa

68616520.0

In [105]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_num[:,0], valor_coringa)

array([False, False, False, ..., False, False, False])

In [106]:
# Podemos checar se uma coluna foi preenchida com o valor coringa
np.isin(arr_num[:,0], valor_coringa).sum()

0

> Vamos criar um array de estatísticas, especificamente valor mínimo, máximo e média de cada variável. Usaremos isso noo tratamento de valores ausentes (preenchidos com o valor coringa).

In [107]:
# Criamos um array com valor mínimo, média e valor máximo ignorando nan
# Usaremos isso no tratamento de valores ausentes
arr_stats = np.array([np.nanmin(dados, axis = 0), media_ignorando_nan, np.nanmax(dados, axis = 0)])

In [108]:
print(arr_stats)

[[  373332.           nan     1000.           nan     1000.           nan        6.         31.42         nan         nan         nan         nan         nan        0.  ]
 [54015809.19         nan    15273.46         nan    15311.04         nan       16.62      440.92         nan         nan         nan         nan         nan     3143.85]
 [68616519.           nan    35000.           nan    35000.           nan       28.99     1372.97         nan         nan         nan         nan         nan    41913.62]]


In [109]:
arr_stats[:, colunas_numericas]

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

## <font color='blue'>Pré-Processamento da Variável funded_amnt</font>

In [110]:
# Visualiza os dados
arr_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [111]:
arr_stats[0, colunas_numericas[2]]

1000.0

In [112]:
# Ajustamos o conteúdo da coluna
arr_num[:,2] = np.where(arr_num[:,2] == valor_coringa, arr_stats[0, colunas_numericas[2]], arr_num[:,2])

In [113]:
arr_num[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

## <font color='blue'>Pré-Processamento das Variáveis loan_amnt, int_rate, installment e total_pymnt</font>

In [114]:
# Nomes das colunas
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [115]:
# Loop para substituir o valor ausente (valor_coringa) pelos valores do array de estatísticas
for i in [1,3,4,5]:
    arr_num[:,i] = np.where(arr_num[:,i] == valor_coringa, 
                                arr_stats[2, colunas_numericas[i]], 
                                arr_num[:,i])

In [116]:
arr_num

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

## <font color='blue'>Trabalhando com o Segundo Dataset</font>

> Vamos carregar os dados de cotação USD - EURO. Cada linha do dataset corresponde à taxa de câmbio para um mês em um ano.

In [117]:
# Carrega o segundo dataset
dados_cot = np.genfromtxt("dados/dataset2.csv", 
                          delimiter = ',', 
                          autostrip = True, 
                          skip_header = 1, 
                          usecols = 3)

In [118]:
# Visualiza
dados_cot

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [119]:
# Nomes de colunas
header_str

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'state_address'], dtype='<U19')

In [120]:
# Dados
arr_str

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [121]:
# A coluna 0 do array de strings é o mês
arr_str[:,0]

array([ 5,  0,  9, ...,  6,  4, 12])

In [122]:
# Vamos atribuir a coluna de mês à variável chamada exchange_rate
exchange_rate = arr_str[:,0]

In [123]:
# Loop para preencher a variável exchange_rate com a taxa correspondente ao mês
# Usamos dados_cot[i - 1] devido a forma como carregamos os meses para comportar o zero
for i in range(1,13):
    exchange_rate = np.where(exchange_rate == i, dados_cot[i - 1], exchange_rate)    

In [124]:
exchange_rate

array([1.1 , 0.  , 1.13, ..., 1.12, 1.11, 1.09])

In [125]:
# Onde a taxa de câmbio estiver com zero substituímos pela média
exchange_rate = np.where(exchange_rate == 0, np.mean(dados_cot), exchange_rate)

In [126]:
exchange_rate

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [127]:
exchange_rate.shape

(10000,)

In [128]:
arr_num.shape

(10000, 6)

In [129]:
exchange_rate = np.reshape(exchange_rate, (10000,1))

In [130]:
# Concatenação dos arrays
arr_num = np.hstack((arr_num, exchange_rate))

In [131]:
# Inclui o nome da coluna no array de nomes de colunas
header_num = np.concatenate((header_num, np.array(['exchange_rate'])))

In [132]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

> Vamos criar colunas para as taxas de câmbio em USD e EURO.

In [133]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'], dtype='<U19')

In [134]:
# Colunas em USD
columns_dollar = np.array([1,2,4,5])

In [135]:
# Visualiza
arr_num[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [136]:
# Shape
arr_num.shape

(10000, 7)

In [137]:
# Loop pelas colunas USD para aplicar a taxa de conversão para EURO
for i in columns_dollar:
    arr_num = np.hstack((arr_num, np.reshape(arr_num[:,i] / arr_num[:,6], (10000,1))))

In [138]:
# Shape
arr_num.shape

(10000, 11)

In [139]:
# Visualiza
arr_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

> Vamos expandir o cabeçalho com as novas colunas.

In [140]:
header_additional = np.array([column_name + '_EUR' for column_name in header_num[columns_dollar]])

In [141]:
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [142]:
header_num = np.concatenate((header_num, header_additional))

In [143]:
header_num

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [144]:
header_num[columns_dollar] = np.array([column_name + '_USD' for column_name in header_num[columns_dollar]])

In [145]:
header_num

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD', 'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [146]:
columns_index_order = [0,1,7,2,8,3,4,9,5,10,6]

In [147]:
header_num = header_num[columns_index_order]

In [148]:
arr_num

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [149]:
arr_num= arr_num[:,columns_index_order]

## <font color='blue'>Pré-Processamento da Variável int_rate</font>

In [150]:
header_num

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [151]:
arr_num[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [152]:
# Vamos apenas dividir por 100
arr_num[:,5] = arr_num[:,5] / 100

In [153]:
arr_num[:,5]

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

## <font color='blue'>Checkpoint com Variáveis Numéricas Limpas e Pré-Processadas</font>
**Checkpoint 3**

In [154]:
checkpoint_numeric = checkpoint("dados/Checkpoint-Numeric", header_num, arr_num)

In [155]:
checkpoint_numeric['arr_0'], checkpoint_numeric['data']

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate', 'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

## <font color="blue">Construindo o Dataset Final</font>

In [156]:
checkpoint_strings['data'].shape

(10000, 6)

In [157]:
checkpoint_numeric['data'].shape

(10000, 11)

In [158]:
# Concatena os arrays
df_final = np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [159]:
df_final

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [160]:
# Verifica se tem valor ausente
np.isnan(df_final).sum()

0

In [161]:
# Concatena os arrays de nomes de colunas
header_full = np.concatenate((checkpoint_numeric['arr_0'], checkpoint_strings['arr_0']))

In [162]:
# Ordenando o dataset
df_final = df_final[np.argsort(df_final[:,0])]

In [163]:
df_final

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [164]:
# Conferindo a ordenação da coluna 0
np.argsort(df_final[:,0])

array([   0,    1,    2, ..., 9997, 9998, 9999])

In [165]:
# Concatena o array de nomes de colunas com o array de dados
df_final = np.vstack((header_full, df_final))

In [166]:
# Salva em disco
np.savetxt("dados/dataset_limpo_preprocessado.csv", 
           df_final, 
           fmt = '%s',
           delimiter = ',')

## DATA SET INICIAL

![title](imagens/Screenshot1.png)

## DATA SET FINAL

![title](imagens/Screenshot2.png)

## Fim